apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: say-hello
      image: registry.access.redhat.com/ubi8/ubi
      command:
        - /bin/bash
      args: ['-c', 'echo Hello World']
      
      
#Run below scripts
#kubectl apply -f ./demo/01-hello.yaml
#tkn task start --showlog hello
      
    
